#!/usr/bin/perl
use Data::Dumper;

if($0=~/gittip_recieves_(.*)/) {
$username=$1;
#print "username $1 \n";
}
else {
     die "you renamed me! you bastard!\n"; }


if ($ARGV[0] && $ARGV[0] eq "config") {
#change hostname if needed, or remove it
print "host_name gittip
graph_title Weekly donations for $username
graph_vtitle USD
graph_args --base 1000 -l 0 --units-exponent 0
graph_scale no
gittip.label USD
";

  exit;
}

$data=`curl https://www.gittip.com/$username/ 2>/dev/null`;

#print $data;


if($data=~/<div class="number">\$<span class="total-receiving">([\d\.,]+)<\/span><\/div>/) {

    $num=$1;
    $num=~s/,//;

}


print "gittip.value $num\n";
