#!/usr/bin/perl
use Data::Dumper;
use LWP::Simple;
use JSON qw( decode_json );     # From CPAN


if ($ARGV[0] && $ARGV[0] eq "config") {
print "host_name bitcoin
graph_title BTC-USD MtGox
graph_vtitle USD
graph_args --base 1000 -l 0
avg.label Avg
high.label High
low.label Low
buy.label Buy
sell.label Sell
";

  exit;
}
 






$json=get("http://data.mtgox.com/api/1/BTCUSD/ticker");

#print Dumper($json);
$data = decode_json( $json );

$avg=$data->{return}->{avg}->{value};
$high=$data->{return}->{high}->{value};
$low=$data->{return}->{low}->{value};
$buy=$data->{return}->{buy}->{value};
$sell=$data->{return}->{sell}->{value};

print "avg.value $avg\n";
print "high.value $high\n";
print "low.value $low\n";
print "buy.value $buy\n";
print "sell.value $sell\n";
